### ISSUE TITLE
[GLPI 9.4.3] Plugin installation errors

### ISSUE THREAD

**Issue by pingax** [karhel/glpi-dporegister#31]
Hi,

I wanted to install the extension on fresh updated 9.4.3 GLPI. After clicking on the install button on plugins management' page, I only got a blank page. 

In the files/_log/php-errors.log, I got these lines : 

```
[2019-08-22 16:44:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): Illegal string offset 'COUNT'
  Backtrace :
  inc/dbutils.class.php:327
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  plugins/dporegister/inc/profile.class.php:279      countElementsInTable()
  plugins/dporegister/inc/profile.class.php:61       PluginDporegisterProfile::initProfile()
  plugins/dporegister/hook.php:74                    PluginDporegisterProfile::install()
  inc/plugin.class.php:521                           plugin_dporegister_install()
  front/plugin.form.php:47       
```

When using the php's built-in server, I got this : 
```

[Thu Aug 22 16:47:19 2019] PHP Fatal error:  Uncaught Error: Access to undeclared static property: PluginDporegisterLawfulBasisModel::$gdprValue in /var/www/html/glpi/plugins/dporegister/inc/processing.class.php:626
Stack trace:
#0 /var/www/html/glpi/plugins/dporegister/inc/lawfulbasismodel.class.php(94): PluginDporegisterProcessing::checkLawfulbasisField()
#1 /var/www/html/glpi/plugins/dporegister/hook.php(74): PluginDporegisterLawfulBasisModel::install(Object(Migration), '1.4')
#2 /var/www/html/glpi/inc/plugin.class.php(521): plugin_dporegister_install()
#3 /var/www/html/glpi/front/plugin.form.php(47): Plugin->install('105')
#4 {main}
  thrown in /var/www/html/glpi/plugins/dporegister/inc/processing.class.php on line 626
[Thu Aug 22 16:47:19 2019] 192.168.1.13:57954 [500]: /front/plugin.form.php - Uncaught Error: Access to undeclared static property: PluginDporegisterLawfulBasisModel::$gdprValue in /var/www/html/glpi/plugins/dporegister/inc/processing.class.php:626
Stack trace:
#0 /var/www/html/glpi/plugins/dporegister/inc/lawfulbasismodel.class.php(94): PluginDporegisterProcessing::checkLawfulbasisField()
#1 /var/www/html/glpi/plugins/dporegister/hook.php(74): PluginDporegisterLawfulBasisModel::install(Object(Migration), '1.4')
#2 /var/www/html/glpi/inc/plugin.class.php(521): plugin_dporegister_install()
#3 /var/www/html/glpi/front/plugin.form.php(47): Plugin->install('105')
#4 {main}
  thrown in /var/www/html/glpi/plugins/dporegister/inc/processing.class.php on line 626
```

**Comment by pingax** [comment]
Hi,

 This bug can be resolved by declaring `static $gdprValue` in `inc/lawfulbasismodel.class.php` 

But now I got a MySQL syntax error when I want to install the plugin (tables in db already exist) : 

`error updating glpi_plugin_dporegister_processings (1) with the new lawfulbasis model You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') WHERE id = 1' at line 2`

Raw query executed (line 629 of `inc/processing.class.php`) : 

`UPDATE `glpi_plugin_dporegister_processings` SET `plugin_dporegister_lawfulbasismodels_id` = (
                        SELECT id FROM `glpi_plugin_dporegister_lawfulbasismodels` WHERE `name` = )
                        WHERE id = 1;`

Seems that the `$name` variable is empty.

**Comment by pingax** [comment]
Hi,

Some precisions on this bug : I'm running php-7.3.11 on Apache 2.4.38. 

This bug seems to occur when the plugin has already been installed on a previous GLPI installation. I also had an SQL syntax error (with existing tables), in file `/inc/processing.class.php`. It seems that `$name = PluginDporegisterLawfulBasisModel::$gdprValue[$resultSet['lawfulbasis']];` does not take any value or take a wrong value, according to plugin's tables.

**Comment by yild** [comment]
modify line 279                 "`name` = '" . $data['field'] . "'"
to 
['name' => $data['field']]
